Revert "Merge tag 'LA.UM.8.1.r1-14300-sm8150.0' of https://source.codeaurora.org/quic/la/platform/packages/services/Telephony into ten"
This reverts commit e6657e14cfc801f5758890fb44390426c0149dd9.

Revert "Telephony: Fix NoClassDefFoundError in TelecomAccountRegistry"

This reverts commit d5cefc39d4988e8b462182d8ac3ee6b577eaa63a.

Revert "Telephony: Break qti-telephony-framework dependency"

This reverts commit 842751fb88cc287cfa143e198dc7f27e72068893.

Revert "Merge tag 'LA.UM.8.1.r1-14500-sm8150.0' of https://source.codeaurora.org/quic/la/platform/packages/services/Telephony into ten"

This reverts commit 9ed8a539be0878d4eac0761f0caea4b88be38470.

Revert "Break MSIM dependency on qti-telephony-framework"

This reverts commit 66d252d61cffc2a7cbaacc54103e7fd1816ca440.

Revert "Merge tag 'LA.UM.8.1.r1-14300-sm8150.0' of https://source.codeaurora.org/quic/la/platform/packages/services/Telephony into ten"

This reverts commit e53352015c8d6178ac6f9659b3f4ac06ada65160.